version: "3.9"

services:
  mysql:
    container_name: reversi-mysql
    image: mysql:8.0.29
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - db_store:/var/lib/mysql

volumes:
  db_store:
