version: "3.9"

services:
  mysql:
    container_name: reversi-mysql
    image: mysql:8.0.29
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reversi
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_store:/var/lib/mysql

volumes:
  db_store:
